import { Accommodation } from "./Interfaces";

export const places: Accommodation[] = [
  {
    id: 1,
    name: "Beach House in Miami",
    location: "Miami, Florida",
    price_per_night: 150,
    property_type: "House",
    amenities: ["Pool", "Ocean View", "WiFi"],
    image_url: "https://example.com/image1.jpg",
  },
  {
    id: 2,
    name: "Downtown Apartment in New York City",
    location: "New York City, New York",
    price_per_night: 200,
    property_type: "Apartment",
    amenities: ["Gym", "Terrace", "WiFi"],
    image_url: "https://example.com/image2.jpg",
  },
  {
    id: 3,
    name: "Mountain Cabin in Colorado",
    location: "Colorado, USA",
    price_per_night: 120,
    property_type: "Cabin",
    amenities: ["Fireplace", "Hot Tub", "Hiking"],
    image_url: "https://example.com/image3.jpg",
  },
  {
    id: 4,
    name: "Villa in Tuscany",
    location: "Tuscany, Italy",
    price_per_night: 300,
    property_type: "Villa",
    amenities: ["Private Pool", "Garden", "Gourmet Kitchen"],
    image_url: "https://example.com/image4.jpg",
  },
  {
    id: 5,
    name: "Private Room in Paris",
    location: "Paris, France",
    price_per_night: 80,
    property_type: "Private Room",
    amenities: ["Breakfast Included", "Near Public Transport", "WiFi"],
    image_url: "https://example.com/image5.jpg",
  },
  {
    id: 6,
    name: "Luxury Apartment in Dubai",
    location: "Dubai, United Arab Emirates",
    price_per_night: 400,
    property_type: "Apartment",
    amenities: ["Daily Cleaning Service", "Panoramic Views", "Rooftop Pool"],
    image_url: "https://example.com/image6.jpg",
  },
  {
    id: 7,
    name: "Country Cottage in English Countryside",
    location: "England, United Kingdom",
    price_per_night: 100,
    property_type: "Country Cottage",
    amenities: ["Fireplace", "Large Garden", "BBQ"],
    image_url: "https://example.com/image7.jpg",
  },
  {
    id: 8,
    name: "Sea View Apartment in Barcelona",
    location: "Barcelona, Spain",
    price_per_night: 150,
    property_type: "Apartment",
    amenities: ["Sea View Terrace", "Near Beach", "WiFi"],
    image_url: "https://example.com/image8.jpg",
  },
  {
    id: 9,
    name: "Countryside House in Tuscany",
    location: "Tuscany, Italy",
    price_per_night: 250,
    property_type: "Countryside House",
    amenities: ["Pool", "Private Garden", "Vineyard Views"],
    image_url: "https://example.com/image9.jpg",
  },
  {
    id: 10,
    name: "Luxury Villa in Bali",
    location: "Bali, Indonesia",
    price_per_night: 500,
    property_type: "Villa",
    amenities: ["Infinity Pool", "Butler Service", "Gourmet Kitchen"],
    image_url: "https://example.com/image10.jpg",
  },
];
